// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraceMonitor.Infrastructure.Data;

#nullable disable

namespace TraceMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(TraceMonitorDbContext))]
    partial class TraceMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraceMonitor.Core.Models.IpGeoCache", b =>
                {
                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Isp")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Org")
                        .HasColumnType("text");

                    b.HasKey("Ip");

                    b.ToTable("IpGeoCache");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.PathChangeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewHopsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousHopsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetId", "DetectedAtUtc");

                    b.ToTable("PathChangeEvents");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.Target", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationHost")
                        .IsUnique();

                    b.ToTable("Targets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DestinationHost = "186.19.218.8",
                            IsActive = true,
                            Name = "Griveo",
                            Provider = "Telecentro"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DestinationHost = "190.210.245.120",
                            IsActive = true,
                            Name = "Vaclog",
                            Provider = "IPLAN"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DestinationHost = "186.23.255.158",
                            IsActive = true,
                            Name = "Managio (DC)",
                            Provider = "Telecentro"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DestinationHost = "186.23.255.156",
                            IsActive = true,
                            Name = "Vaclog (DC)",
                            Provider = "Telecentro"
                        });
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.TraceHop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Avg")
                        .HasColumnType("double precision");

                    b.Property<double>("Best")
                        .HasColumnType("double precision");

                    b.Property<int>("HopIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<double>("Last")
                        .HasColumnType("double precision");

                    b.Property<double>("LossPct")
                        .HasColumnType("double precision");

                    b.Property<int>("Sent")
                        .HasColumnType("integer");

                    b.Property<double>("StDev")
                        .HasColumnType("double precision");

                    b.Property<long>("TraceRunId")
                        .HasColumnType("bigint");

                    b.Property<double>("Worst")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TraceRunId");

                    b.ToTable("TraceHops");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.TraceRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("HopCount")
                        .HasColumnType("integer");

                    b.Property<double>("OverallAvgRttMs")
                        .HasColumnType("double precision");

                    b.Property<double>("OverallLossPct")
                        .HasColumnType("double precision");

                    b.Property<int>("PacketsSent")
                        .HasColumnType("integer");

                    b.Property<string>("PathHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetId", "StartedAtUtc");

                    b.ToTable("TraceRuns");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.PathChangeEvent", b =>
                {
                    b.HasOne("TraceMonitor.Core.Models.Target", "Target")
                        .WithMany("Events")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.TraceHop", b =>
                {
                    b.HasOne("TraceMonitor.Core.Models.TraceRun", "TraceRun")
                        .WithMany("Hops")
                        .HasForeignKey("TraceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraceRun");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.TraceRun", b =>
                {
                    b.HasOne("TraceMonitor.Core.Models.Target", "Target")
                        .WithMany("Runs")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.Target", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("TraceMonitor.Core.Models.TraceRun", b =>
                {
                    b.Navigation("Hops");
                });
#pragma warning restore 612, 618
        }
    }
}
